ECommerce/Controllers/CategoriesController.cs
using ECommerce.Data;
using ECommerce.Data.Services;
using ECommerce.Data.Static;
using ECommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CategoriesController : Controller
    {
        private readonly ICategoryServices _services;
        public CategoriesController(ICategoryServices services)
        {
            _services = services;
        }
        public async Task<IActionResult> Index()
        {
            var Response = await _services.GetAllAsync();
            return View(Response);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                await _services.CreateAsync(category);
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var category = await _services.GetByIdAsync(id);
            if (category != null)
            {
                return View(category);
            }
            return View("NotFound");
        }
        public async Task<IActionResult> Edit(int id)
        {
            var category = await _services.GetByIdAsync(id);
            if (category != null)
            {
                return View(category);
            }
            return View("NotFound");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View("NotFound");

            }
            await _services.UpdateAsync(category);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _services.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

ECommerce/Controllers/OrdersController.cs
using ECommerce.Data.Cart;
using ECommerce.Data.Services;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ECommerce.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IProductServices _services;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderServices _orderServices;

        public OrdersController(IProductServices services, ShoppingCart shoppingCart, IOrderServices orderServices)
        {
            _services = services;
            _shoppingCart = shoppingCart;
            _orderServices = orderServices;
        }
        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string roleId = User.FindFirstValue(ClaimTypes.Role);
            var order = await _orderServices.GetOrderAndRoleByUserIdAsync(userId, roleId);
            return View(order);
        }
        public IActionResult ShoppingCart()
        {
            var item = _shoppingCart.GetShoppingCartItems();
            ViewBag.Total = _shoppingCart.GetShoppingCartTotal();
            return View(item);
        }
        public async Task<IActionResult> AddToCart(int id)
        {
            var item = await _services.GetByIdAsync(id);
            if (item != null)
            {
                await _shoppingCart.AddItemToShoppingCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> RemoveFromCart(int id)
        {
            var item = await _services.GetByIdAsync(id);
            if (item != null)
            {
                await _shoppingCart.RemoveItemFromShoppingCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _orderServices.StoreOrderAsync(items, userId);
            _shoppingCart.ClearShoppingCart();
            return View("CompleteOrder");
        }

    }
}

ECommerce/Controllers/ProductsController.cs
using ECommerce.Data;
using ECommerce.Data.Services;
using ECommerce.Data.Static;
using ECommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]

    public class ProductsController : Controller
    {
        private readonly IProductServices _services;
        private readonly ICategoryServices _categoryServices;
        public ProductsController(IProductServices services, ICategoryServices categoryServices)
        {
            _services = services;
            _categoryServices = categoryServices;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index(string searchTerm)
        {
            var Response = await _services.GetAllAsync(x => x.Category);
            if (!string.IsNullOrEmpty(searchTerm))
            {
                Response = Response.Where(x => x.Name.Contains(searchTerm)).ToList();
            }
            return View(Response);
        }
        [AllowAnonymous]

        public async Task<IActionResult> Details(int id)
        {
            var Product = await _services.GetByIdAsync(id, x => x.Category);
            return View(Product);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.CategoryId = await _categoryServices.GetAllAsync();
            return View();
        }
        [HttpPost, ActionName(nameof(Create))]
        public async Task<IActionResult> CreateProduct(Product product)
        {
            if (ModelState.IsValid)
            {
                await _services.CreateAsync(product);
                return RedirectToAction(nameof(Index));
            }
            return View("NotFound");
        }
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.Category = await _categoryServices.GetAllAsync();
            var productId = await _services.GetByIdAsync(id, x => x.Category);
            return View(productId);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                //Update
                await _services.UpdateAsync(product);
                return RedirectToAction("Index");
            }
            return View(product);
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _services.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

ECommerce/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Not Found";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <img src="" style="width:80%;height:500px;" />
    </div>
    <div class="col-md-4 offset-5">
        <a class="btn btn-outline-success" asp-action="Index" asp-controller="Products">
            <i class="fas fa-regular fa-arrow-rotate-right"></i>
            Go To Home Page</a>
    </div>
</div>

ECommerce/Views/Shared/_CreateItem.cshtml
@model string;
 @if (Context.User.Identity.IsAuthenticated && User.IsInRole("Admin"))
 {
<div class="text-white" style="position:fixed;right:30px;bottom:100px;">
    <a asp-action="Create" asp-controller="@Model" class="btn btn-outline-success">
        <i class="fas fa-regular fa-plus-square mr-2"></i>
        Create</a>
</div>
 }

ECommerce/Views/Shared/_Identity.cshtml
@using Microsoft.AspNetCore.Identity

@inject UserManager<ApplicationUser> _userManager;
@if(!User.Identity.IsAuthenticated){
<a class="btn btn-outline-success mr-2" asp-action="Login" asp-controller="Account">
    <i class="fas fa-regular fa-arrow-right-to-bracket"></i> Login
</a>
<a class="btn btn-outline-secondary mr-2" asp-action="Register" asp-controller="Account">
    <i class="fas fa-regular fa-user-check"></i> Register
</a>
}
else{
<div class="dropdown">
    <button class="btn  btn-outline-info dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown" aria-expanded="false">
        <i class="fas fa-person mr-2"></i> Hello,@_userManager.GetUserName(User)
    </button>
    <div class="dropdown-menu" aria-labelledby="profile-btn">
        <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
            <i class="fas fa-regular fa-list-check mr-2"></i> Orders
        </a>
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
               
                <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                    <i class="fas fa-regular fa-users mr-2"></i> Users
                </a>
            }
        <form asp-controller="Account" asp-action="Logout">
            <hr />
            <button class="dropdown-item">
                <i class="fas fa-duotone fa-arrow-right-from-bracket"></i>
                Logout
            </button>
        </form>
    </div>
</div>
}

ECommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Products" asp-action="Index">
                    <i class="fas fa-duotone fa-cart-arrow-down"></i>
                    ECommerce
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Product</a>
                            </li>
                        }
                    </ul>
                    <form class="form-inline" style="padding-right=30px;" asp-action="Index" asp-controller="Products">
                        <input name="searchTerm" type="text" class="form-control" placeholder="Search here..." autocomplete="off" />
                        <button type="submit" class="btn btn-outline-info">
                            <i class="fas fa-regular fa-search"></i>
                        </button>
                    </form>
                    <ul class="navbar-nav mr-2">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>
                    <partial name="_Identity" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <i class="fas fa-duotone fa-cart-arrow-down"></i>
            &copy; 2022 - ECommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>